export const SEARCH_TERM_REQUEST = 'SEARCH_TERM_REQUEST'
export const SEARCH_TERM_SUCESS = 'SEARCH_TERM_SUCESS'
export const SEARCH_TERM_FAIL = 'SEARCH_TERM_FAIL'

export const SEARCH_DETAIL_REQUEST = 'SEARCH_DETAIL_REQUEST'
export const SEARCH_DETAIL_SUCESS = 'SEARCH_DETAIL_SUCESS'
export const SEARCH_DETAIL_FAIL = 'SEARCH_DETAIL_FAIL'